[package]
name = "routes"
version.workspace = true
edition.workspace = true

[dependencies]
axum.workspace = true
tower.workspace = true
sqlx.workspace = true
reqwest.workspace = true
serde.workspace = true
tower-http.workspace = true
tracing.workspace = true
anyhow.workspace = true
rand.workspace = true
thiserror.workspace = true
settings = { path = "../settings" }
telemetry = { path = "../telemetry" }
email-client = { path = "../email-client" }
domain = { path = "../domain" }
