[package]
name = "routes"
version.workspace = true
edition.workspace = true

[dependencies]
axum.workspace = true
tower.workspace = true
sqlx.workspace = true
reqwest.workspace = true
serde.workspace = true
tower-http.workspace = true
tracing.workspace = true
anyhow.workspace = true
rand.workspace = true
thiserror.workspace = true

settings.workspace = true
telemetry.workspace = true
email-client.workspace = true
domain.workspace = true
state.workspace = true
hakari-hack.workspace = true

[dev-dependencies]
tokio.workspace = true
wiremock.workspace = true
linkify.workspace = true
serde_json.workspace = true
