[package]
name = "axum-error-helper"
version.workspace = true
authors.workspace = true
edition.workspace = true
categories.workspace = true
repository.workspace = true

[lib]
proc-macro = true

[dependencies]
deluxe = "0.5.0"
proc-macro2 = "1.0.103"
quote = "1.0.42"
syn = "2.0.111"
