[package]
name = "service"
version.workspace = true
edition.workspace = true

[dependencies]
repository.workspace = true
async-trait = "0.1.86"
thiserror.workspace = true
anyhow.workspace = true
tracing.workspace = true
