[package]
name = "server"
version.workspace = true
edition.workspace = true

[dependencies]
sqlx.workspace = true
tokio.workspace = true
axum.workspace = true
email-client = { path = "../email-client" }
routes = { path = "../routes" }
settings = { path = "../settings" }
telemetry = { path = "../telemetry" }
